version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g @angular/cli
      - npm install
  pre_build:
    commands:
      - echo "Retrieving environment variables"
      - export API_KEY=$(aws ssm get-parameters --names "/myapp/firebase/apiKey" --with-decryption --query "Parameters[0].Value" --output text)
      - export AUTH_DOMAIN=$(aws ssm get-parameters --names "/myapp/firebase/authDomain" --with-decryption --query "Parameters[0].Value" --output text)
      - export PROJECT_ID=$(aws ssm get-parameters --names "/myapp/firebase/projectId" --with-decryption --query "Parameters[0].Value" --output text)
      - export STORAGE_BUCKET=$(aws ssm get-parameters --names "/myapp/firebase/storageBucket" --with-decryption --query "Parameters[0].Value" --output text)
      - export MESSAGING_SENDER_ID=$(aws ssm get-parameters --names "/myapp/firebase/messagingSenderId" --with-decryption --query "Parameters[0].Value" --output text)
      - export APP_ID=$(aws ssm get-parameters --names "/myapp/firebase/appId" --with-decryption --query "Parameters[0].Value" --output text)
      - export MEASUREMENT_ID=$(aws ssm get-parameters --names "/myapp/firebase/measurementId" --with-decryption --query "Parameters[0].Value" --output text)
  build:
    commands:
      - echo "Building the project"
      - sed -i "s|\${API_KEY}|$API_KEY|g" src/environments/environment.base.ts
      - sed -i "s|\${AUTH_DOMAIN}|$AUTH_DOMAIN|g" src/environments/environment.base.ts
      - sed -i "s|\${PROJECT_ID}|$PROJECT_ID|g" src/environments/environment.base.ts
      - sed -i "s|\${STORAGE_BUCKET}|$STORAGE_BUCKET|g" src/environments/environment.base.ts
      - sed -i "s|\${MESSAGING_SENDER_ID}|$MESSAGING_SENDER_ID|g" src/environments/environment.base.ts
      - sed -i "s|\${APP_ID}|$APP_ID|g" src/environments/environment.base.ts
      - sed -i "s|\${MEASUREMENT_ID}|$MEASUREMENT_ID|g" src/environments/environment.base.ts
      - ng build --production
  post_build:
    commands:
      - echo "Build completed on `date`"
